config/routes.rb
Rails.application.routes.draw do
  root "saml#index"
  post "/fingerprint", to: "saml#fingerprint"
  post "/decode",      to: "saml#decode"
  post "/encode",      to: "saml#encode"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/saml_controller.rb
class SamlController < ApplicationController

  def index
  end

  def fingerprint
    data = "-----BEGIN CERTIFICATE-----\n" + params[:content].delete("\r") + "\n-----END CERTIFICATE-----\n"
    cert = OpenSSL::X509::Certificate.new(data)
    @content = OpenSSL::Digest::SHA1.hexdigest(cert.to_der).scan(/../).map{ |s| s.upcase }.join(":")
  end

  def encode
    @content = Base64.encode64(params[:content])
  end

  def decode
    @content = Base64.decode64(params[:content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samltool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/saml/decode.html.erb
<pre>
<%= @content %>
</pre>

app/views/saml/encode.html.erb
<%= @content %>

app/views/saml/fingerprint.html.erb
<%= @content %>

app/views/saml/index.html.erb
<%= form_tag fingerprint_path do %>
  <%= text_area_tag :content, nil, rows: 10, cols: 50 %>
  <%= submit_tag "Calculate Fingerprint" %>
<% end %>

<%= form_tag encode_path do %>
  <%= text_area_tag :content, nil, rows: 10, cols: 50 %>
  <%= submit_tag "Base64 Encode" %>
<% end %>

<%= form_tag decode_path do %>
  <%= text_area_tag :content, nil, rows: 10, cols: 50 %>
  <%= submit_tag "Base64 Decode" %>
<% end %>